#!/usr/bin/env bash

if [[ $1 = "create" ]] ; then
  mkdir -p ~/.cabin/apps/${2}
  
fi

if [[ $1 = "reset proxy" ]] ; then
  curl -L -o ~/.cabin/traefik/docker-compose.yml https://raw.githubusercontent.com/EmilMoe/traefik-proxy/main/docker-compose.yml
fi

if [[ $1 = "selfupdate" ]] ; then
  curl -L -o /usr/local/bin/cabin https://raw.githubusercontent.com/EmilMoe/traefik-proxy/main/docker-compose.yml
  chmod +x /usr/locale/bin/cabin
fi
