#!/usr/bin/env bash

if [[ $1 = "create" ]] ; then
  mkdir -p ~/.cabin/apps/${2}
  
fi

if [[ $1 = "reset-proxy" ]] ; then
  rm ~/.cabin/setup_webserver
  curl -sL https://raw.githubusercontent.com/EmilMoe/cabin/main/setup_webserver.sh | bash -
fi

if [[ $1 = "selfupdate" ]] ; then
  curl -L -o /usr/local/bin/cabin https://raw.githubusercontent.com/EmilMoe/cabin/main/cabin
  chmod +x /usr/local/bin/cabin
fi
